{% set name = "fbprophet" %}
{% set version = "0.4.post1" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "dfc1eb2836dc609dc0075822d969e8d908b0e42219b44cfe40c544de7cb0561b" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt
  features:
    - vc9   # [win and py27]
    - vc14  # [win and py>=35]
  binary_has_prefix_files:
    - Lib/site-packages/fbprophet/stan_model/prophet_model.pkl          # [win]
    - lib/python*/site-packages/fbprophet/stan_model/prophet_model.pkl  # [unix]

requirements:
  build:
    - toolchain  # [unix]
    - python
    - setuptools
    - cython >=0.22
    - pystan >=2.14
    # Pystan models depend on numpy and as they are compiled and pickled we
    # need to pin numpy version. Note that 1.10 is not available for win+py36.
    - numpy 1.10.*  # [not win or py<=35]
    - numpy 1.11.*  # [win and py>=36]

  run:
    - python
    - matplotlib >=2.0.0
    - pandas >=0.20.1
    - pystan >=2.14
    - numpy >=1.10  # [not win or py<=35]
    - numpy >=1.11  # [win and py>=36]
    # setuptools is required for pkg_resources
    - setuptools
    
test:
  requires:
    - pytest

  commands:
    - py.test -v --pyargs fbprophet

about:
  home: https://facebook.github.io/prophet/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Automatic Forecasting Procedure'
  description: |
    Implements a procedure for forecasting time series data based on an
    additive model where non-linear trends are fit with yearly, weekly, and
    daily seasonality, plus holiday effects. It works best with time series
    that have strong seasonal effects and several seasons of historical data.
    Prophet is robust to missing data and shifts in the trend, and typically
    handles outliers well.
  doc_url: https://facebook.github.io/prophet/docs/quick_start.html
  dev_url: https://github.com/facebook/prophet

extra:
  recipe-maintainers:
    - pmlandwehr
    - rmax
