travis:
  secure:
    BINSTAR_TOKEN: jkyggvAEo4uNP3CdmWFaM39BF8dWVdaiYRCzRsT+nGkP1rXLRPO+2r5bbUoOK3BYSoRz4LfHhvwIkcW4dVOzTAWakLTvInarOl3amMhaL4tKqoVMc6m2Tet5Ie6p2Bgd+z0ppTPhz+8ODkHwhfZyC+jpR/UxjoiQo+5HZhy1QDfvdbvB0dV4zFS0axjDsxSbJJVKwCwfkUWds/WnIGc6MUwwWcBdpmcqMVTuVPal0jdsIvFGjftldlQEG6/AT4rEbRCSOZUlzW5sbkSe2v8H15KmFugFkxHdcN5EgIV++zxEGg19TTtVt6yd74CbI8dei0hJ4ClyOAZMIuaDe5P1oK3DrDUWwA57T3b2rjNdmsrd511eh88l5QfksmU3H5WLY8yWH1H9WDt+JpEHQhBaJNbrWCCBiB+gwNs7tcg4rTxyE3vv+a3nKqEPfUwov/QOutxT4WClx65oo2IiPsbioi/0wAVT6JD3uORfm+PomIyy5f8bNQIV0ZjAIXXJ6bHsd1/KXxkxMq6x+RVXqbHBdjOCq8T4hRoyWiZovUviqz0cb+0Yq2TbnVuBxwPmD3CZYn5fgR8ltqtP2ncdnR2qRm04VnHiwk+4FxexKxn8bZGU0u7sdFih6GVeNmMa06t4veeEQh3psJ/kkPUFtee99GElO6y8jScPcKqOdGj/RhU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
